#!/usr/bin/env python3
"""Build _data/courses/*.yml from editable schedule CSVs.

One CSV per course-semester, one row per class meeting, in the format documented in
teaching-src/schedule-format.md. For each course registered in teaching-src/courses.json
the CSV is looked up in two places, in order:

  1. ~/teaching/<source_csv>          — the teaching library's copy, if it exists.
     This is the one the instructor edits during the semester; it always wins.
  2. teaching-src/schedules/<csv>     — the copy kept in this repo, used until the
     teaching library has one.

Blank topic / reading cells for a numbered lecture are filled from the typed lecture
notes, so the CSV only has to carry the calendar.

    ./teaching-src/gen_courses.py            # rebuild every course
    ./teaching-src/gen_courses.py stat400-2026-fall
"""
from __future__ import annotations

import csv
import datetime as dt
import json
import os
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
HERE = REPO / "teaching-src"
TEACHING = pathlib.Path(os.environ.get("TEACHING_ROOT", pathlib.Path.home() / "teaching"))
TYPED = TEACHING / "courses/STAT400/lectures/typed/lectures"
OUT = REPO / "_data/courses"

KINDS = {"lecture", "review", "exam", "final", "holiday"}


def typed_lectures() -> dict[int, tuple[str, str]]:
    """lecture number -> (title, Devore sections), read from the typed notes."""
    found = {}
    for tex in sorted(TYPED.glob("lec*.tex")):
        m = re.search(r"\\lecture\{(\d+)\}\{(.+?)\}\{(.+?)\}", tex.read_text(encoding="utf-8")[:400], re.S)
        if m:
            found[int(m.group(1))] = (m.group(2), m.group(3).replace("\\ ", " ").replace("--", "\u2013"))
    return found


def q(s: str) -> str:
    return '"' + str(s).replace("\\", "").replace('"', '\\"').strip() + '"'


def week_span(first: dt.date) -> str:
    mon = first - dt.timedelta(days=first.weekday())
    return f"{mon.strftime('%b %-d')} \u2013 {(mon + dt.timedelta(days=6)).strftime('%b %-d')}"


def read_rows(path: pathlib.Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        rows = [r for r in csv.DictReader(fh) if (r.get("date") or "").strip()]
    for i, r in enumerate(rows, 2):
        for k, v in list(r.items()):
            r[k] = (v or "").strip()
        try:
            dt.date.fromisoformat(r["date"])
        except ValueError:
            raise SystemExit(f"{path}:{i}: date must be YYYY-MM-DD, got {r['date']!r}")
        if r["kind"] not in KINDS:
            raise SystemExit(f"{path}:{i}: kind must be one of {sorted(KINDS)}, got {r['kind']!r}")
        if not r["week"].isdigit():
            raise SystemExit(f"{path}:{i}: week must be a number, got {r['week']!r}")

    # Rows render in file order, so file order has to be the calendar order. Catching a
    # shuffled row here beats publishing a schedule that reads out of sequence.
    for (i, prev), (j, cur) in zip(enumerate(rows, 2), enumerate(rows[1:], 3)):
        if dt.date.fromisoformat(cur["date"]) <= dt.date.fromisoformat(prev["date"]):
            raise SystemExit(f"{path}:{j}: dates must increase down the file "
                             f"({cur['date']} follows {prev['date']})")
        if int(cur["week"]) < int(prev["week"]):
            raise SystemExit(f"{path}:{j}: week numbers must not go backwards "
                             f"(week {cur['week']} follows week {prev['week']})")
    return rows


def build(key: str, spec: dict, lectures: dict[int, tuple[str, str]]) -> pathlib.Path:
    src = TEACHING / spec["source_csv"]
    origin = "the teaching library"
    if not src.exists():
        src = HERE / "schedules" / spec["csv"]
        origin = "this repo (the teaching library has no schedule.csv yet)"
    rows = read_rows(src)

    # Consecutive rows carrying the same week number form one week block.
    weeks: list[tuple[int, list[dict]]] = []
    for r in rows:
        w = int(r["week"])
        if not weeks or weeks[-1][0] != w:
            weeks.append((w, []))
        weeks[-1][1].append(r)

    meta = spec["meta"]
    out = [
        f"# {meta['code']} \u2014 {meta['term']}",
        "#",
        f"# GENERATED by teaching-src/gen_courses.py from {src.name} in {origin}.",
        "# Edit the CSV, not this file. Titles and readings left blank in the CSV are",
        "# filled from the typed lecture notes.",
        "",
    ]
    for k, v in meta.items():
        if isinstance(v, bool):
            out.append(f"{k}: {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            out.append(f"{k}: {v}")
        elif len(str(v)) > 90:
            out.append(f"{k}: >-")
            out.append("  " + str(v))
        else:
            out.append(f"{k}: {q(v)}")
    out.append("schedule:")

    for week, group in weeks:
        first_date = dt.date.fromisoformat(group[0]["date"])
        out.append(f"  - week: {week}")
        out.append(f"    span: {q(week_span(first_date))}")
        out.append("    meetings:")
        for r in group:
            date = dt.date.fromisoformat(r["date"])
            out.append(f"      - date: {r['date']}")
            out.append(f"        day: {q(date.strftime('%a'))}")
            out.append(f"        kind: {r['kind']}")
            title, reading = r["topic"], r["reading"]
            if r["lecture"].isdigit():
                n = int(r["lecture"])
                # Only courses that follow the typed notes' own lecture numbering may
                # borrow titles and readings from them; other terms numbered differently.
                fallback = lectures.get(n) if spec.get("notes_numbering") else None
                if fallback:
                    title = title or fallback[0]
                    reading = reading or fallback[1]
                out.append(f"        lecture: {n}")
                if spec.get("link_notes") and (REPO / f"files/stat400/notes/lec{n:02d}.pdf").exists():
                    out.append(f"        notes: /files/stat400/notes/lec{n:02d}.pdf")
            out.append(f"        title: {q(title or r['kind'].title())}")
            if reading:
                out.append(f"        reading: {q('Devore ' + reading)}")

        # Homework and quizzes belong to the week: take the first row that carries them.
        hw = next((r for r in group if r["hw"]), None)
        if hw:
            out.append("    hw:")
            out.append(f"      id: {hw['hw']}")
            if hw["hw_posted"]:
                out.append(f"      posted: {hw['hw_posted']}")
            if hw["hw_due"]:
                out.append(f"      due: {hw['hw_due']}")
            if hw["note"]:
                out.append(f"      note: {q(hw['note'])}")
        quiz = next((r["quiz"] for r in group if r["quiz"]), None)
        if quiz:
            out.append(f"    quiz: {q(quiz)}")

    dest = OUT / f"{key}.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    return dest


def main() -> int:
    registry = json.loads((HERE / "courses.json").read_text(encoding="utf-8"))
    wanted = sys.argv[1:] or list(registry)
    lectures = typed_lectures()
    for key in wanted:
        if key not in registry:
            raise SystemExit(f"unknown course {key!r}; known: {', '.join(registry)}")
        dest = build(key, registry[key], lectures)
        print(f"wrote {dest.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
