"""Emit _data/courses/stat400-2026-fall.yml.

Lecture titles/readings come from the typed-notes project
(~/teaching/courses/STAT400/lectures/typed/lectures/lecNN.tex).
Calendar dates come from the UMD Fall 2026 semester calendar.
HW rhythm mirrors Fall 2025 (posted Friday, due the next Friday).
"""
import datetime as dt
import re
import pathlib

TYPED = pathlib.Path.home() / "teaching/courses/STAT400/lectures/typed/lectures"

lectures = {}
for tex in sorted(TYPED.glob("lec*.tex")):
    head = tex.read_text(encoding="utf-8")[:400]
    m = re.search(r"\\lecture\{(\d+)\}\{(.+?)\}\{(.+?)\}", head, re.S)
    n, title, reading = int(m.group(1)), m.group(2), m.group(3)
    reading = reading.replace("\\ ", " ").replace("--", "\u2013")
    lectures[n] = (title, reading)
assert len(lectures) == 26, len(lectures)

# (week, [(date, kind, payload), ...], hw, quiz)
# kind: lecture -> payload = lecture number; exam/holiday -> payload = label
S = [
    (1,  [("09-01", "lecture", 1), ("09-03", "lecture", 2)], None, None),
    (2,  [("09-08", "lecture", 3), ("09-10", "lecture", 4)], ("HW1", "09-11", "09-18"), "Quiz 1"),
    (3,  [("09-15", "lecture", 5), ("09-17", "lecture", 6)], ("HW2", "09-18", "09-25"), "Quiz 2"),
    (4,  [("09-22", "lecture", 7), ("09-24", "lecture", 8)], ("HW3", "09-25", "10-02"), "Quiz 3"),
    (5,  [("09-29", "lecture", 9), ("10-01", "lecture", 10)], ("HW4", "10-02", "10-09"), "Quiz 4"),
    (6,  [("10-06", "lecture", 11), ("10-08", "exam", "Midterm 1")], None, None),
    (7,  [("10-13", "holiday", "Fall Break \u2014 no class"), ("10-15", "lecture", 12)],
         ("HW5", "10-16", "10-23"), "Quiz 5"),
    (8,  [("10-20", "lecture", 13), ("10-22", "lecture", 14)], ("HW6", "10-23", "10-30"), "Quiz 6"),
    (9,  [("10-27", "lecture", 15), ("10-29", "lecture", 16)], ("HW7", "10-30", "11-06"), "Quiz 7"),
    (10, [("11-03", "lecture", 17), ("11-05", "exam", "Midterm 2")], None, None),
    (11, [("11-10", "lecture", 18), ("11-12", "lecture", 19)], ("HW8", "11-13", "11-20"), "Quiz 8"),
    (12, [("11-17", "lecture", 20), ("11-19", "lecture", 21)], ("HW9", "11-20", "11-24"), "Quiz 9"),
    (13, [("11-24", "lecture", 22), ("11-26", "holiday", "Thanksgiving \u2014 no class")], None, None),
    (14, [("12-01", "lecture", 23), ("12-03", "lecture", 24)], ("HW10", "12-04", "12-11"), "Quiz 10"),
    (15, [("12-08", "lecture", 25), ("12-10", "lecture", 26)], None, None),
    (16, [("12-14", "final", "Final Exam \u00b7 date set by the Registrar")], None, None),
]


def esc(s):
    return '"' + s.replace('\\', '').replace('"', '\\"') + '"'


out = []
w = out.append
w("# STAT 400 / DATA 400 \u2014 Fall 2026")
w("#")
w("# Lecture titles and Devore sections are transcribed from the typed lecture notes")
w("# (~/teaching/courses/STAT400/lectures/typed/). Semester dates follow the UMD Fall 2026")
w("# academic calendar: classes 08-31 \u2192 12-11, Fall Break 10-12/13, Thanksgiving 11-25/29,")
w("# finals 12-14 \u2192 12-21.")
w("#")
w("# TENTATIVE: midterm dates, homework dates and quiz numbering are drafted from the")
w("# Fall 2025 rhythm and are not confirmed. Fields marked TBD await the official syllabus.")
w("#")
w("# GENERATED by teaching-src/gen_stat400_fall2026.py — edit that script, not this file.")
w("")
w("code: STAT 400 / DATA 400")
w("name: Applied Probability and Statistics I")
w("term: Fall 2026")
w("status: current")
w("tentative: true")
w("institution: University of Maryland")
w("instructor: Shixin Zheng")
w("office: 2303 Kirwan Hall")
w("email: siuzheng@umd.edu")
w("meetings: TuTh 2:00\u20133:15 pm (TBD)")
w("room: TBD")
w("sections: TBD")
w("discussion: TBD")
w("office_hours: TBD")
w("ta: TBD")
w("elms: https://elms.umd.edu")
w("first_day: 2026-08-31")
w("last_day: 2026-12-11")
w("finals: 2026-12-14 \u2013 2026-12-21")
w("textbook: >-")
w("  Lecture notes by J. F. Fernandes and M. D. Gunatilleka; reference text")
w("  Devore, <em>Probability and Statistics for Engineering and the Sciences</em>, 9th ed.")
w("notes_pdf: /files/stat400/notes/stat400-lecture-notes.pdf")
w("notes_pages: 109")
w("schedule:")

for week, meetings, hw, quiz in S:
    first = dt.date.fromisoformat("2026-" + meetings[0][0])
    monday = first - dt.timedelta(days=first.weekday())
    sunday = monday + dt.timedelta(days=6)
    span = f"{monday.strftime('%b %-d')} \u2013 {sunday.strftime('%b %-d')}"
    w(f"  - week: {week}")
    w(f"    span: {esc(span)}")
    w("    meetings:")
    for date, kind, payload in meetings:
        d = dt.date.fromisoformat("2026-" + date)
        w(f"      - date: 2026-{date}")
        w(f"        day: {d.strftime('%a')}")
        w(f"        kind: {kind}")
        if kind == "lecture":
            title, reading = lectures[payload]
            w(f"        lecture: {payload}")
            w(f"        title: {esc(title)}")
            w(f"        reading: {esc('Devore ' + reading)}")
            w(f"        notes: /files/stat400/notes/lec{payload:02d}.pdf")
        else:
            w(f"        title: {esc(payload)}")
    if hw:
        hid, posted, due = hw
        w("    hw:")
        w(f"      id: {hid}")
        w(f"      posted: 2026-{posted}")
        w(f"      due: 2026-{due}")
    if quiz:
        w(f"    quiz: {esc(quiz + ' \u00b7 in discussion')}")

path = pathlib.Path(__file__).resolve().parent.parent / "_data/courses/stat400-2026-fall.yml"
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {path} ({len(out)} lines)")
